services:
  db:
    image: mysql:8.4.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: me

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
