services:
  todo_db:
    image: mysql:8.4.5
    volumes:
      - ./todo_db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - todo_network

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    depends_on:
        - todo_db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - todo_network

  jre21:
    image: openjdk:21-jdk
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
        - phpmyadmin
    volumes:
      - ./app:/app
    working_dir: /app
    command: [ "java", "-jar", "todo.jar" ]
    ports:
      - "8080:8080"
    networks:
      - todo_network
  caddy:
    image: caddy:2.9.1
    restart: always
    depends_on:
      - jre21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
